# üêº Pandas Practice: DataFrames, Selection, Mapping, and More

In [47]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Sample data
names = ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona', 'George', 'Hannah']
departments = ['Sales', 'Marketing', 'HR', 'Tech']

# Create a DataFrame
df = pd.DataFrame({
    'Name': np.random.choice(names, size=20),
    'Age': np.random.randint(22, 60, size=20),
    'Department': np.random.choice(departments, size=20),
    'Salary': np.random.randint(40000, 120000, size=20),
    'YearsExperience': np.random.randint(0, 20, size=20)
})
df.head()

      Name  Age Department  Salary  YearsExperience
0   George   43         HR   75920               15
1    Diana   23  Marketing  107121               12
2    Ethan   45       Tech  109479               17
3   George   51      Sales   59457               14
4  Charlie   59       Tech  106557               12

# üß™ PRACTICE QUESTIONS BELOW


# 1Ô∏è‚É£ Use .loc to select all rows where the Department is 'Tech'.
#    - Describe what .loc does and why it's useful for label-based filtering.

In [48]:
df.loc[df['Department'] == 'Tech']
#.loc is used in Pandas to access rows and columns in a DataFrame using labels .It is especially useful when you want to filter or select data based on column names, row indexes, or conditions.

       Name  Age Department  Salary  YearsExperience
2     Ethan   45       Tech  109479               17
4   Charlie   59       Tech  106557               12
12  Charlie   49       Tech  111211               11
13  Charlie   37       Tech  105697                7
15    Ethan   24       Tech   72606               18
17   Hannah   28       Tech   80397                7
19  Charlie   30       Tech   95591                2


# 2Ô∏è‚É£ Use .iloc to select the first 5 rows and the last two columns.
#    - What is the difference between .loc and .iloc?

In [49]:
df.iloc[:5, -2:]
# .loc  selects rows ,columns by labels
# .iloc selects rows, columns by integer positions

   Salary  YearsExperience
0   75920               15
1  107121               12
2  109479               17
3   59457               14
4  106557               12


# 3Ô∏è‚É£ Map a new column called 'DeptCode' where:
#     'Sales' -> 1, 'Marketing' -> 2, 'HR' -> 3, 'Tech' -> 4.
#    - Use .map and explain what happens if a value is not mapped.

In [50]:
df['DeptCode'] = df['Department'].map({'Sales': 1, 'Marketing': 2, 'HR': 3, 'Tech': 4})
df[['Department', 'DeptCode']].head()
# .map is used to transform values in a Series using a dictionary or function.
# If a value is not found in the mapping dictionary, it becomes NaN.

  Department  DeptCode
0         HR         3
1  Marketing         2
2       Tech         4
3      Sales         1
4       Tech         4


# 4Ô∏è‚É£ Use .apply to calculate a new column 'Seniority' where:
#     - If YearsExperience > 10 ‚Üí 'Senior'
#     - If between 5-10 ‚Üí 'Mid-Level'
#     - Else ‚Üí 'Junior'
#    - Use a lambda function with apply.

In [51]:
df['Seniority'] = df['YearsExperience'].apply(lambda x: 'Senior' if x > 10 else 'Mid-Level' if x >= 5 else 'Junior')
df[['YearsExperience', 'Seniority']]

    YearsExperience  Seniority
0                15     Senior
1                12     Senior
2                17     Senior
3                14     Senior
4                12     Senior
5                 8  Mid-Level
6                14     Senior
7                12     Senior
8                 0     Junior
9                 6  Mid-Level
10                8  Mid-Level
11                0     Junior
12               11     Senior
13                7  Mid-Level
14               10  Mid-Level
15               18     Senior
16               16     Senior
17                7  Mid-Level
18                2     Junior
19                2     Junior


# 5Ô∏è‚É£ Overwrite all salaries for employees with < 3 years of experience to 35000.
#    - Use boolean indexing with .loc to do this.

In [52]:
df.loc[df['YearsExperience'] < 3, 'Salary'] = 35000
df[df['YearsExperience'] < 3][['YearsExperience', 'Salary']]

    YearsExperience  Salary
8                 0   35000
11                0   35000
18                2   35000
19                2   35000


# 6Ô∏è‚É£ Compare using .loc and .iloc to select the same row:
#    - Select the 3rd row using .iloc
#    - Find its index value and use .loc to select the same row by label

In [53]:
df.iloc[2]

Name                Ethan
Age                    45
Department           Tech
Salary             109479
YearsExperience        17
DeptCode                4
Seniority          Senior
Name: 2, dtype: object

In [54]:
df.loc[df.index[2]]

Name                Ethan
Age                    45
Department           Tech
Salary             109479
YearsExperience        17
DeptCode                4
Seniority          Senior
Name: 2, dtype: object


# 7Ô∏è‚É£ Check if there are any duplicate names in the dataset.
#    - If there are, show only those duplicated rows.

In [55]:
df[df.duplicated('Name', keep=False)]

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
1     Diana   23  Marketing  107121               12         2     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
15    Ethan   24       Tech   72606               18         4     Senior
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior


# 8Ô∏è‚É£ Sort the DataFrame by Salary in descending order.
#    - Then sort it by Department and within Department by Age.

In [56]:
df.sort_values(by='Salary', ascending=False)

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
6     Ethan   42  Marketing  118953               14         2     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
12  Charlie   49       Tech  111211               11         4     Senior
2     Ethan   45       Tech  109479               17         4     Senior
1     Diana   23  Marketing  107121               12         2     Senior
4   Charlie   59       Tech  106557               12         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
7     Ethan   54  Marketing   92995               12         2     Senior
10  Charlie   46      Sales   85758                8         1  Mid-Level
17   Hannah   28       Tech   80397                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
0    George   43         HR   75920               15         3     Senior
15    Ethan   24       Tech   72606               18         4     Senior
3    George   51      Sales   59457               14         1     Senior
16    Diana   58         HR   51534               16         3     Senior
9       Bob   43  Marketing   49692                6         2  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
8    George   33      Sales   35000                0         1     Junior
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior

In [57]:
df.sort_values(by=['Department', 'Age'])

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
14   Hannah   36         HR   77065               10         3  Mid-Level
0    George   43         HR   75920               15         3     Senior
16    Diana   58         HR   51534               16         3     Senior
1     Diana   23  Marketing  107121               12         2     Senior
5    Hannah   23  Marketing  117189                8         2  Mid-Level
6     Ethan   42  Marketing  118953               14         2     Senior
9       Bob   43  Marketing   49692                6         2  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
18   Hannah   42      Sales   35000                2         1     Junior
10  Charlie   46      Sales   85758                8         1  Mid-Level
3    George   51      Sales   59457               14         1     Senior
15    Ethan   24       Tech   72606               18         4     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
19  Charlie   30       Tech   35000                2         4     Junior
13  Charlie   37       Tech  105697                7         4  Mid-Level
2     Ethan   45       Tech  109479               17         4     Senior
12  Charlie   49       Tech  111211               11         4     Senior
4   Charlie   59       Tech  106557               12         4     Senior


# 9Ô∏è‚É£ Slice the DataFrame to return rows 5 through 12 and columns 'Name', 'Salary'
#    - Try slicing using both label-based and position-based methods.

In [58]:
df.loc[5:12, ['Name', 'Salary']]

       Name  Salary
5    Hannah  117189
6     Ethan  118953
7     Ethan   92995
8    George   35000
9       Bob   49692
10  Charlie   85758
11   George   35000
12  Charlie  111211

In [59]:
df.iloc[5:13, [df.columns.get_loc('Name'), df.columns.get_loc('Salary')]]

       Name  Salary
5    Hannah  117189
6     Ethan  118953
7     Ethan   92995
8    George   35000
9       Bob   49692
10  Charlie   85758
11   George   35000
12  Charlie  111211


# üîü Find all rows where the name starts with 'A' or 'D'.
#    - Use string methods with .str accessor.

In [60]:
df[df['Name'].str.startswith(('A', 'D'))]

     Name  Age Department  Salary  YearsExperience  DeptCode Seniority
1   Diana   23  Marketing  107121               12         2    Senior
16  Diana   58         HR   51534               16         3    Senior


# 1Ô∏è‚É£1Ô∏è‚É£ Drop all rows where Age is below 25.
#     - Explain whether this modifies the DataFrame in place or returns a copy.

In [61]:
df[df['Age'] >= 25]

       Name  Age Department  Salary  YearsExperience  DeptCode  Seniority
0    George   43         HR   75920               15         3     Senior
2     Ethan   45       Tech  109479               17         4     Senior
3    George   51      Sales   59457               14         1     Senior
4   Charlie   59       Tech  106557               12         4     Senior
6     Ethan   42  Marketing  118953               14         2     Senior
7     Ethan   54  Marketing   92995               12         2     Senior
8    George   33      Sales   35000                0         1     Junior
9       Bob   43  Marketing   49692                6         2  Mid-Level
10  Charlie   46      Sales   85758                8         1  Mid-Level
11   George   48  Marketing   35000                0         2     Junior
12  Charlie   49       Tech  111211               11         4     Senior
13  Charlie   37       Tech  105697                7         4  Mid-Level
14   Hannah   36         HR   77065               10         3  Mid-Level
16    Diana   58         HR   51534               16         3     Senior
17   Hannah   28       Tech   80397                7         4  Mid-Level
18   Hannah   42      Sales   35000                2         1     Junior
19  Charlie   30       Tech   35000                2         4     Junior


# 1Ô∏è‚É£2Ô∏è‚É£ Use groupby to calculate the average salary per Department.
#     - Bonus: Show the average age and average experience too.

In [62]:
df.groupby('Department')[['Salary', 'Age', 'YearsExperience']].mean()

                  Salary        Age  YearsExperience
Department
HR          68173.000000  45.666667        13.666667
Marketing   86825.000000  38.833333         8.666667
Sales       53803.750000  43.000000         6.000000
Tech        88706.714286  38.857143        10.571429


# 1Ô∏è‚É£3Ô∏è‚É£ Use groupby to count how many employees are in each Department.

In [63]:
df['Department'].value_counts()

Department
Tech         7
Marketing    6
Sales        4
HR           3
Name: count, dtype: int64


# 1Ô∏è‚É£4Ô∏è‚É£ Use .apply to normalize the Salary column (min-max scaling between 0 and 1).
#     - Bonus: Write your own normalization function and pass it to apply.

In [64]:
def normalize(col):
    return (col - col.min()) / (col.max() - col.min())

df['NormalizedSalary'] = df['Salary'].apply(lambda x: normalize(df['Salary'])[df[df['Salary'] == x].index[0]])
df[['Salary', 'NormalizedSalary']].head(10)

   Salary  NormalizedSalary
0   75920          0.487416
1  107121          0.859064
2  109479          0.887151
3   59457          0.291318
4  106557          0.852346
5  117189          0.978988
6  118953          1.000000
7   92995          0.690803
8   35000          0.000000
9   49692          0.175003


# 1Ô∏è‚É£5Ô∏è‚É£ Use boolean indexing to find all employees who:
#     - Are in 'HR' OR 'Tech', AND have > 5 years of experience.

# üîÅ For many of these tasks, try both .loc and .iloc to build intuition on their differences.

In [65]:
df.loc[(df['Department'].isin(['HR', 'Tech'])) & (df['YearsExperience'] > 5)]

,Name,Age,Department,Salary,YearsExperience,DeptCode,Seniority,NormalizedSalary
0,George,43,HR,75920,15,3,Senior,0.487416
2,Ethan,45,Tech,109479,17,4,Senior,0.887151
4,Charlie,59,Tech,106557,12,4,Senior,0.852346
12,Charlie,49,Tech,111211,11,4,Senior,0.907782
13,Charlie,37,Tech,105697,7,4,Mid-Level,0.842102
14,Hannah,36,HR,77065,10,3,Mid-Level,0.501054
15,Ethan,24,Tech,72606,18,4,Senior,0.447941
16,Diana,58,HR,51534,16,3,Senior,0.196944
17,Hannah,28,Tech,80397,7,4,Mid-Level,0.540743

In [66]:
dep_col = df.columns.get_loc('Department')
exp_col = df.columns.get_loc('YearsExperience')

df.iloc[((df.iloc[:, dep_col].isin(['HR', 'Tech'])) & (df.iloc[:, exp_col] > 5)).values]

,Name,Age,Department,Salary,YearsExperience,DeptCode,Seniority,NormalizedSalary
0,George,43,HR,75920,15,3,Senior,0.487416
2,Ethan,45,Tech,109479,17,4,Senior,0.887151
4,Charlie,59,Tech,106557,12,4,Senior,0.852346
12,Charlie,49,Tech,111211,11,4,Senior,0.907782
13,Charlie,37,Tech,105697,7,4,Mid-Level,0.842102
14,Hannah,36,HR,77065,10,3,Mid-Level,0.501054
15,Ethan,24,Tech,72606,18,4,Senior,0.447941
16,Diana,58,HR,51534,16,3,Senior,0.196944
17,Hannah,28,Tech,80397,7,4,Mid-Level,0.540743